name: Generate Snake animation
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        with:
          github_user_name: srbatista2
          svg_out_path: dist/github-contribution-grid-snake.svg
